Add appflinger.h with types for key modifier and js key code
tversity/appflinger-go pull request #3
Opened 2021-11-22 21:23 UTC by alinabrus

2021-11-22 23:19 UTC, ronenmiz requested changes

2021-11-22 23:19 UTC, ronenmiz commented on libappflinger/appflinger.h
> +typedef enum
@alinabrus Let's add a comment explaining that these are the constant used for modifiers when injecting input events via `/osb/session/event`

2021-11-22 23:19 UTC, ronenmiz commented on libappflinger/appflinger.h
> +typedef enum
@alinabrus Let's add a comment that these are the javascript key codes expected by the AppFlinger server. Any given client platform needs to establish a mapping from its native key codes to this one prior to sending it to the AppFlinger server via `/osb/session/event`

Let's also fix the indentatio of the commented codes or maybe just get rid of the comments and always assign a value. ok?

2021-11-30 13:14 UTC, alinabrus commented on libappflinger/appflinger.h
> +typedef enum
@ronenmiz I've made changes but indentations still not always good. I'm not sure how to fix them because on my machine everything looks correct.

2021-11-30 15:02 UTC, ronenmiz commented on libappflinger/appflinger.h
> +typedef enum
@alinabrus That's fine

2021-12-20 16:12 UTC, merged